### ISSUE TITLE
Publish to the GitHub actions marketplace?

### ISSUE THREAD

**Issue by AdamCoulterOz** [hashicorp/ghaction-terraform-provider-release#22]

**Comment by bflad** [comment]
Hi @AdamCoulterOz 👋  Thank you for raising this question.

Do you have a particular motivation for having this action published to the marketplace? If it is for discoverability, that is certainly a decent request, but I am curious if there was also potentially missing documentation that might have helped as well.

One challenge here is that this repository currently contains two reusable release workflows, one for community releases and one for HashiCorp internal releases. The [marketplace publishing requirements](https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace) state that each repository must only contain one action. While this is a solvable issue, potentially by splitting it into two separate repositories or other solutions, it does currently represent something that would immediately prevent this publishing from occurring.

**Comment by bflad** [comment]
Closing due to lack of response. If you have a response to the above or other commentary, we can certainly revisit this topic.
